SELECT NAME, USERID, PWD, EMAIL, PHONE, ADMIN, JOINDATE
FROM MEMBER;

SELECT NAME, USERID, PWD, EMAIL, PHONE, ADMIN, JOINDATE
FROM MEMBER
WHERE USERID = 'parkgy';

INSERT INTO MEMBER (NAME, USERID, PWD, EMAIL, PHONE, ADMIN)
values('박규영', 'parkgy', '1234', 'pgy@gamil.com', '010-1111-2222', 0);

UPDATE MEMBER
SET name='문채원', pwd='5678', email='mcw@gmail.com', phone='010-3333-5555', ADMIN=1, JOINDATE='2020-08-20'
WHERE userid = 'parkgy';

DELETE 
FROM MEMBER
WHERE userid = 'parkgy';





